### ISSUE TITLE
[hw2] Add more hints in 4f

### ISSUE THREAD

**Issue by syed-ahmed** [icgrp/ese532_handouts#4]
Add links to 4f:
- https://developer.arm.com/documentation/den0024/a/The-A64-instruction-set/Memory-access-instructions/Load-instruction-format
- https://developer.arm.com/documentation/den0024/a/The-A64-instruction-set/Memory-access-instructions/Specifying-the-address-for-a-Load-or-Store-instruction

**Comment by ept221** [comment]
Resources added to part 4.
